## You should change each of the following fields
## to customize your blog

title: "The Best Stats Blog You'll Ever Find"
description: "This is a place for me to blog about stats and make sure I get a good grade in stat 386" 
author: Jessa Halversen
author_description: "I am an Applied Statistics and Analytics student at BYU who's just tryin to graduate :)" 

url: https://jessahal.github.io ## change this to https://yourusername.github.io
baseurl: /blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  jessahal
    twitter: 
    facebook: 
    email: 
    linkedin: jessa-halversen
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




