## You should change each of the following fields
## to customize your blog

title: "The Ramblings of a Starving Stats Major"
description: "This started as a place for me to blog about stats in order to get a good grade in my classes, but now it's a place for me to share some fo the things I've learned in my journey as a stats major!" 
author: Jessa Halversen
author_description: "I'm an Applied Statistics and Analytics major from BYU (Go Cougs)! The reason I fell in love with statistics is because I realized how powerful and important data can be in every aspect of our lives. I love problem solving and finding ways to use data analysis to optimize different processes and find new solutions. " 

url: https://jessahal.github.io ## change this to https://yourusername.github.io
baseurl: /blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  jessahal
    twitter: 
    facebook: 
    email: 
    linkedin: jessa-halversen
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




